print("Now downloading 3rd party programs.")
print("I don't host these, the files download from the original pastebin.")
print("DISCLAIMER: I DID NOT MAKE THESE.")
sleep(3)
print("--------Enter program name below--------")
local file = read()
local path = http.get("https://theslaymann.github.io/slayds/content/programs/3rd_party/".. file ..".3rd")
program = fs.open("slaydsfiles/program", "w")
program.write(path.readAll())
program.close()
path.close()
shell.run("slaydsfiles/program")
